### ISSUE TITLE
testUpdate testCreate in UserApiTest passed but failed create and update in UserApi

### ISSUE THREAD

**Issue by dreamsbond** [limoncello-php/framework#50]
./vendor/bin/phpunit --filter testUpdate ./tests/UserApiTest.php
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.18
Configuration: /limoncello-php/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 857 ms, Memory: 12.00MB

OK (1 test, 11 assertions)

./vendor/bin/phpunit --filter testCreate ./tests/UserApiTest.php
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.18
Configuration: /limoncello-php/phpunit.xml

.                                                                   1 / 1 (100%)
Time: 783 ms, Memory: 12.00MB

OK (1 test, 7 assertions)

passed in UserApiTest

but failed in postman

{"errors":[{"code":"403","title":"Unauthorized","detail":"You are not unauthorized for action `canManageUsers`.","source":{"pointer":"/data"}}]}

**Comment by neomerx** [comment]
@dreamsbond Update will be today.

**Comment by neomerx** [comment]
Jasper, it's fixed. I remember you very good ) Don't hesitate to ask and I'll be happy to answer. Sorry I missed your questions in gitter (don't ready it often).
